- name: Install nginx
  pacman: name=nginx

- name: Install logrotate config
  copy: src=logrotate.conf dest=/etc/logrotate.d/nginx-ansible owner=root group=root mode=0644

- name: Enable nginx
  service: name=nginx enabled=yes